import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { ThemeProvider } from "@/components/Theme/theme-provider";
import "../fonts.css";
import Footer from "@/components/Footer/Footer";
import Providers from "./Providers";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir={`ltr`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-farsi-primary`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <div className="w-full">
              <div className="  flex flex-col sm:max-w-[1440px] mx-auto md:px-8 w-full min-h-200">
                <Navbar />
                {children}
              </div>
              <Footer />
            </div>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
