import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/layout/Navbar/Navbar";
import { ThemeProvider } from "@/components/Theme/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import Footer from "@/components/Footer/Footer";
import Providers from "./Providers";
import { getDictionary } from "@/lib/getDictionary";
import { TranslationProvider } from "@/app/[locale]/TranslationContext";
import LanguageSwitcher from "@/components/LanguageSwitcher";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = (await params) || {};
  const dict = await getDictionary(locale);
  return (
    <html lang={locale} dir={locale === "en" ? "ltr" : "rtl"}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-farsi-primary`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <TranslationProvider dict={dict}>
              <div className="w-full">
                <div className="  flex flex-col sm:max-w-[1440px] mx-auto md:px-8 w-full min-h-200">
                  <Navbar />
                  {children}
                </div>
                <Footer />
              </div>
              <LanguageSwitcher currentLocale={locale} />
              <Toaster />
            </TranslationProvider>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
